name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Deploy Documentation"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository # Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Pages # Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact # Upload the docs directory as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages # Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4